In [4]:
import numpy as np
import pandas as pd
import ast

In [5]:
movies = pd.read_csv('datasets/bollywood.csv')
movies

,Movie_Name,Release Period,Whether Remake,Whether Franchise,Genre,New Actor,New Director,New Music Director,Lead_Star,Director,Music_Director,Number of Screens,Revenue(INR),Budget(INR)
0,Golden Boys,Normal,No,No,suspense,Yes,No,No,Jeet Goswami,Ravi Varma,Baba Jagirdar,5,5000000,85000
1,Kaccha Limboo,Holiday,No,No,drama,Yes,No,Yes,Karan Bhanushali,Sagar Ballary,Amardeep Nijjer,75,15000000,825000
2,Not A Love Story,Holiday,No,No,thriller,No,No,No,Mahie Gill,Ram Gopal Verma,Sandeep Chowta,525,75000000,56700000
3,Qaidi Band,Holiday,No,No,drama,Yes,No,No,Aadar Jain,Habib Faisal,Amit Trivedi,800,210000000,4500000
4,Chaatwali,Holiday,No,No,adult,Yes,Yes,Yes,Aadil Khan,Aadil Khan,Babloo Ustad,1,1000000,1075000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1693,Fight Club,Holiday,No,No,action,No,Yes,No,Zayed Khan,Vikram Chopra,Pritam,375,82500000,88862500
1694,Strings Of Paasion,Normal,No,No,drama,No,Yes,Yes,Zeenat Aman,Sanghamitra Chaudhuri,Dev Sikdar,10,8000000,70000
1695,Dunno Y Na Jaane Kyun,Normal,No,No,drama,No,No,No,Zeenat Aman,Sanjay Sharma,Nikhil,20,12500000,850000
1696,Taj Mahal - An Eternal Love Story,Normal,No,No,drama,No,Yes,No,Zulfi Sayed,Akbar Khan,Naushad,135,100000000,31065000
1697,Mr. Hot Mr. Kool,Normal,No,No,comedy,No,No,Yes,Zulfi Sayed,Partho Ghosh,Rishi - Ranjit,30,27500000,1300000

In [6]:
movies = movies[['Movie_Name', 'Genre','Lead_Star','Director','Music_Director']]
movies

,Movie_Name,Genre,Lead_Star,Director,Music_Director
0,Golden Boys,suspense,Jeet Goswami,Ravi Varma,Baba Jagirdar
1,Kaccha Limboo,drama,Karan Bhanushali,Sagar Ballary,Amardeep Nijjer
2,Not A Love Story,thriller,Mahie Gill,Ram Gopal Verma,Sandeep Chowta
3,Qaidi Band,drama,Aadar Jain,Habib Faisal,Amit Trivedi
4,Chaatwali,adult,Aadil Khan,Aadil Khan,Babloo Ustad
...,...,...,...,...,...
1693,Fight Club,action,Zayed Khan,Vikram Chopra,Pritam
1694,Strings Of Paasion,drama,Zeenat Aman,Sanghamitra Chaudhuri,Dev Sikdar
1695,Dunno Y Na Jaane Kyun,drama,Zeenat Aman,Sanjay Sharma,Nikhil
1696,Taj Mahal - An Eternal Love Story,drama,Zulfi Sayed,Akbar Khan,Naushad
1697,Mr. Hot Mr. Kool,comedy,Zulfi Sayed,Partho Ghosh,Rishi - Ranjit

In [7]:
movies.isnull().sum()

Movie_Name        0
Genre             0
Lead_Star         0
Director          0
Music_Director    0
dtype: int64

In [8]:
movies.dropna(inplace = True)

C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\3024812739.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace = True)

In [9]:
movies.duplicated().sum()

np.int64(3)

In [10]:
movies.iloc[0].Genre

'suspense'

In [11]:
def to_list(val):
    try:
        return ast.literal_eval(val)
    except (ValueError, SyntaxError):
        return [val]  # just wrap it in a list if eval fails

In [12]:
movies['Genre'] = movies['Genre'].apply(to_list)

C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\4076070913.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['Genre'] = movies['Genre'].apply(to_list)

In [13]:
movies.head()

,Movie_Name,Genre,Lead_Star,Director,Music_Director
0,Golden Boys,[suspense],Jeet Goswami,Ravi Varma,Baba Jagirdar
1,Kaccha Limboo,[drama],Karan Bhanushali,Sagar Ballary,Amardeep Nijjer
2,Not A Love Story,[thriller],Mahie Gill,Ram Gopal Verma,Sandeep Chowta
3,Qaidi Band,[drama],Aadar Jain,Habib Faisal,Amit Trivedi
4,Chaatwali,[adult],Aadil Khan,Aadil Khan,Babloo Ustad

In [14]:
movies['Lead_Star'] = movies['Lead_Star'].apply(to_list)
movies['Director'] = movies['Director'].apply(to_list)
movies['Music_Director'] = movies['Music_Director'].apply(to_list)

C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\3376465930.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['Lead_Star'] = movies['Lead_Star'].apply(to_list)
C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\3376465930.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['Director'] = movies['Director'].apply(to_list)
C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\3376465930.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['Music_Director'] = movies['Music_Director'].apply(to_list)

In [15]:
movies.head()

,Movie_Name,Genre,Lead_Star,Director,Music_Director
0,Golden Boys,[suspense],[Jeet Goswami],[Ravi Varma],[Baba Jagirdar]
1,Kaccha Limboo,[drama],[Karan Bhanushali],[Sagar Ballary],[Amardeep Nijjer]
2,Not A Love Story,[thriller],[Mahie Gill],[Ram Gopal Verma],[Sandeep Chowta]
3,Qaidi Band,[drama],[Aadar Jain],[Habib Faisal],[Amit Trivedi]
4,Chaatwali,[adult],[Aadil Khan],[Aadil Khan],[Babloo Ustad]

In [16]:
movies['Genre'] = movies['Genre'].apply(lambda x:[i.replace(" ","_") for i in x])
movies['Lead_Star'] = movies['Lead_Star'].apply(lambda x:[i.replace(" ","_") for i in x])
movies['Director'] = movies['Director'].apply(lambda x:[i.replace(" ","_") for i in x])
movies['Music_Director'] = movies['Music_Director'].apply(lambda x:[i.replace(" ","_") for i in x])

C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\3941607683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['Genre'] = movies['Genre'].apply(lambda x:[i.replace(" ","_") for i in x])
C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\3941607683.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['Lead_Star'] = movies['Lead_Star'].apply(lambda x:[i.replace(" ","_") for i in x])
C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\3941607683.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['Director'] = movies['Director'].apply(lambda x:[i.replace(" ","_") for i in x])
C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\3941607683.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['Music_Director'] = movies['Music_Director'].apply(lambda x:[i.replace(" ","_") for i in x])

In [17]:
movies.head()

,Movie_Name,Genre,Lead_Star,Director,Music_Director
0,Golden Boys,[suspense],[Jeet_Goswami],[Ravi_Varma],[Baba_Jagirdar]
1,Kaccha Limboo,[drama],[Karan_Bhanushali],[Sagar_Ballary],[Amardeep_Nijjer]
2,Not A Love Story,[thriller],[Mahie_Gill],[Ram_Gopal_Verma],[Sandeep_Chowta]
3,Qaidi Band,[drama],[Aadar_Jain],[Habib_Faisal],[Amit_Trivedi]
4,Chaatwali,[adult],[Aadil_Khan],[Aadil_Khan],[Babloo_Ustad]

In [18]:
movies['tags'] = movies['Genre'] + movies['Lead_Star'] + movies['Director'] + movies['Music_Director']

C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\2539448645.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['Genre'] + movies['Lead_Star'] + movies['Director'] + movies['Music_Director']

In [19]:
movies.head()

,Movie_Name,Genre,Lead_Star,Director,Music_Director,tags
0,Golden Boys,[suspense],[Jeet_Goswami],[Ravi_Varma],[Baba_Jagirdar],"[suspense, Jeet_Goswami, Ravi_Varma, Baba_Jagi..."
1,Kaccha Limboo,[drama],[Karan_Bhanushali],[Sagar_Ballary],[Amardeep_Nijjer],"[drama, Karan_Bhanushali, Sagar_Ballary, Amard..."
2,Not A Love Story,[thriller],[Mahie_Gill],[Ram_Gopal_Verma],[Sandeep_Chowta],"[thriller, Mahie_Gill, Ram_Gopal_Verma, Sandee..."
3,Qaidi Band,[drama],[Aadar_Jain],[Habib_Faisal],[Amit_Trivedi],"[drama, Aadar_Jain, Habib_Faisal, Amit_Trivedi]"
4,Chaatwali,[adult],[Aadil_Khan],[Aadil_Khan],[Babloo_Ustad],"[adult, Aadil_Khan, Aadil_Khan, Babloo_Ustad]"

In [20]:
df = movies[['Movie_Name','tags']]
df

,Movie_Name,tags
0,Golden Boys,"[suspense, Jeet_Goswami, Ravi_Varma, Baba_Jagi..."
1,Kaccha Limboo,"[drama, Karan_Bhanushali, Sagar_Ballary, Amard..."
2,Not A Love Story,"[thriller, Mahie_Gill, Ram_Gopal_Verma, Sandee..."
3,Qaidi Band,"[drama, Aadar_Jain, Habib_Faisal, Amit_Trivedi]"
4,Chaatwali,"[adult, Aadil_Khan, Aadil_Khan, Babloo_Ustad]"
...,...,...
1693,Fight Club,"[action, Zayed_Khan, Vikram_Chopra, Pritam]"
1694,Strings Of Paasion,"[drama, Zeenat_Aman, Sanghamitra_Chaudhuri, De..."
1695,Dunno Y Na Jaane Kyun,"[drama, Zeenat_Aman, Sanjay_Sharma, Nikhil]"
1696,Taj Mahal - An Eternal Love Story,"[drama, Zulfi_Sayed, Akbar_Khan, Naushad]"
1697,Mr. Hot Mr. Kool,"[comedy, Zulfi_Sayed, Partho_Ghosh, Rishi_-_Ra..."

In [21]:
df["tags"] = df['tags'].apply(lambda x:" ".join(x))

C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\2811592155.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["tags"] = df['tags'].apply(lambda x:" ".join(x))

In [22]:
df["tags"] = df["tags"].apply(lambda x:x.lower())

C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\3213508868.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["tags"] = df["tags"].apply(lambda x:x.lower())

In [23]:
df.head()

         Movie_Name                                               tags
0       Golden Boys     suspense jeet_goswami ravi_varma baba_jagirdar
1     Kaccha Limboo  drama karan_bhanushali sagar_ballary amardeep_...
2  Not A Love Story  thriller mahie_gill ram_gopal_verma sandeep_ch...
3        Qaidi Band         drama aadar_jain habib_faisal amit_trivedi
4         Chaatwali           adult aadil_khan aadil_khan babloo_ustad

In [24]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [25]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [26]:
df['tags'].apply(stem)

0           suspens jeet_goswami ravi_varma baba_jagirdar
1       drama karan_bhanushali sagar_ballari amardeep_...
2       thriller mahie_gil ram_gopal_verma sandeep_chowta
3                drama aadar_jain habib_fais amit_trivedi
4                adult aadil_khan aadil_khan babloo_ustad
                              ...
1693               action zayed_khan vikram_chopra pritam
1694    drama zeenat_aman sanghamitra_chaudhuri dev_si...
1695               drama zeenat_aman sanjay_sharma nikhil
1696                   drama zulfi_say akbar_khan naushad
1697         comedi zulfi_say partho_ghosh rishi_-_ranjit
Name: tags, Length: 1698, dtype: object

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')
vectors = cv.fit_transform(df['tags']).toarray()

In [28]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]], shape=(1698, 2459))

In [29]:
cv.get_feature_names_out()

array(['_adhiyaman', '_ajay', '_ajay_kumar', ..., 'zubin_balaporia',
       'zubunnisa_bangash', 'zulfi_sayed'], shape=(2459,), dtype=object)

In [30]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)
similarity

array([[1.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 1.       , 0.       , ..., 0.25     , 0.25     ,
        0.       ],
       [0.       , 0.       , 1.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.25     , 0.       , ..., 1.       , 0.25     ,
        0.       ],
       [0.       , 0.25     , 0.       , ..., 0.25     , 1.       ,
        0.2236068],
       [0.       , 0.       , 0.       , ..., 0.       , 0.2236068,
        1.       ]], shape=(1698, 1698))

In [31]:
df["Movie_Name"] = df["Movie_Name"].apply(lambda x:x.lower())

C:\Users\poornima kulkarni\AppData\Local\Temp\ipykernel_6000\4027387479.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Movie_Name"] = df["Movie_Name"].apply(lambda x:x.lower())

In [32]:
df

,Movie_Name,tags
0,golden boys,suspense jeet_goswami ravi_varma baba_jagirdar
1,kaccha limboo,drama karan_bhanushali sagar_ballary amardeep_...
2,not a love story,thriller mahie_gill ram_gopal_verma sandeep_ch...
3,qaidi band,drama aadar_jain habib_faisal amit_trivedi
4,chaatwali,adult aadil_khan aadil_khan babloo_ustad
...,...,...
1693,fight club,action zayed_khan vikram_chopra pritam
1694,strings of paasion,drama zeenat_aman sanghamitra_chaudhuri dev_si...
1695,dunno y na jaane kyun,drama zeenat_aman sanjay_sharma nikhil
1696,taj mahal - an eternal love story,drama zulfi_sayed akbar_khan naushad
1697,mr. hot mr. kool,comedy zulfi_sayed partho_ghosh rishi_-_ranjit

In [42]:
def recommend(movie):
    # Check if movie exists in the DataFrame
    if movie not in df['Movie_Name'].values:
        print(f"'{movie}' not found in dataset.")
        return

    # Get index using reset index logic
    movie_index = df[df['Movie_Name'] == movie].index
    movie_index = movie_index[0]

    # Fix: convert movie_index to positional index (0-based) if new_df index is not 0-based
    movie_index = df.reset_index().query("Movie_Name == @movie").index[0]

    # Now safe to use in similarity
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    for i in movie_list:
        print(df.iloc[i[0]].Movie_Name)

In [43]:
recommend('mr. hot mr. kool')

shuttlecock boys
malegaon me gadbad ghotala
khota sikka - jaat ke thaath
oye lucky! lucky oye!
ek chalis ki last local

In [45]:
import joblib

# Save the necessary components
joblib.dump(df, 'movies_df.joblib',compress=5)
joblib.dump(similarity, 'similarity_matrix.joblib',compress=5)
joblib.dump(cv, 'count_vectorizer.joblib',compress=5)

['count_vectorizer.joblib']